version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  backend:
    build: .
    container_name: fastapi-app
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      - FIREBASE_KEY_PATH=/app/service_account_key.json
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - REDIS_HOST=redis        # <-- 추가
      - REDIS_PORT=6379         # <-- 추가
    volumes:
      - ./service_account_key.json:/app/service_account_key.json
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
