apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: FIREBASE_KEY_PATH
              value: /app/service_account_key.json
            - name: POSTGRES_DB
              value: opensw_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_PORT
              value: "5432"
            - name: REDIS_DB
              value: "0"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          image: fastapi-app:local
          name: fastapi-app
          imagePullPolicy: IfNotPresent  # Docker Hub에서 찾지 못하게 설정
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: firebase-key-volume  # secret_account_key을 변환한 
              mountPath: /app/service_account_key.json 
              subPath: service_account_key.json
              readOnly: true
      restartPolicy: Always
      volumes:
          - name: firebase-key-volume      
            secret:                       
              secretName: firebase-key-secret