name: 4. Backend Code Quality Check (Linting)
on: [push, pull_request]

jobs:
  lint-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Backend # 백엔드 프로젝트 루트 경로
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install Lint Tools
        run: pip install black isort flake8
        
      - name: Run Black Code Formatter Check
        # --check 플래그를 사용하여 포맷팅 오류가 있으면 실패하도록 설정
        run: black --check .
        
      - name: Run Flake8 Linter
        run: flake8 .
        
      - name: Run Isort Import Sort Check
        run: isort --check-only .