name: Backend API Test
on: [push, pull_request]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        # 모든 'run' 스텝의 기본 작업 디렉토리를 'backend'로 설정
        working-directory: ./Backend

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run Pytest
        run: pytest