# .github/workflows/dart.yml
name: Dart

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Cache pub packages
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        working-directory: Frontend/poc_app_usage/
        run: dart pub get

      - name: Analyze project source
        working-directory: Frontend/poc_app_usage/
        run: dart analyze

      - name: Run tests
        working-directory: Frontend/poc_app_usage/
        run: dart test
