name: Flutter Widget Test
on: [push, pull_request]

jobs:
  widget-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./Frontend/poc_app_usage

    steps:
      - uses: actions/checkout@v4
      
      # Flutter SDK 설정
      - uses: subosito/flutter-action@v2
        with:
          # Flutter 버전을 명시
          flutter-version: 3.35.7 
          
      - name: Get Dependencies
        run: flutter pub get 
        
      # 2. 테스트 실행 (working-directory: ./frontend 적용)
      # 'frontend' 폴더 내의 'test/widgets' 경로에서 테스트를 실행
      - name: Run Widget Tests
        run: flutter test test/widgets